### ISSUE TITLE
Create package.json 

### ISSUE THREAD

**Issue by Sebastian-Fitzner** [Veams/veams-component-skip-nav#1]
Hi,

Just get rid of the bower.json and create a package.json instead.

**Comment by estellechvl** [comment]
What should be in the package.json tho ? Same content as the bower.json ?

**Comment by Sebastian-Fitzner** [comment]
Almost, just take a look at other components ;) https://github.com/Veams/veams-component-slider/blob/dev/package.json

**Comment by estellechvl** [comment]
updated :)
